---
language: python
python: "2.7"

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Update apt
  - sudo apt-get update

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook with ansible-playbook
  - ansible-playbook tests/test.yml -i tests/inventory

  # Check the tools are installed
  - curl --version
  - dos2unix --version
  - glances --version
  - grc --version
  - htop --version
  - mtr --version
  - multitail -V
  - ag --version
  - tree --version
  - wget --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
