---
- name: install common command line tools
  become: yes
  apt:
    name:
      - curl
      - dos2unix
      - glances
      - graphviz
      - grc
      - htop
      - httpie
      - jq
      - mtr
      - multitail
      - neofetch
      - shellcheck
      - silversearcher-ag
      - tree
      - wget
    state: present
